### ISSUE TITLE
Plugins load from remote or from local source

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#167]
Currently the plugins can only load from a path on disk. Code is here https://github.com/aspect-build/aspect-cli/blob/0f230e151e57b5b539a11b28b4ec8216f211a27b/pkg/plugin/client/client.go#L57

Users should be able to write
- `from: github.com/my-org/my-plugin@1.2.3` to install a plugin hosted remotely
- `from: //path/to/plugin-target` to use a plugin that's authored in the local repository

**Comment by alexeagle** [comment]
When would we `bazel build` the plugin(s)? Let's always run the `bazel build` every time.
Need to make sure that build command doesn't thrash the analysis cache.
Maybe this is just a local dev convenience, and real users should fetch remote.

**Comment by mattem** [comment]
@alexeagle Can this be closed, or is there further work to be done under this ticket?

**Comment by alexeagle** [comment]
`from: github.com/my-org/my-plugin@1.2.3` is actually the most important part I think.

https://aspect.build/help/topics/plugins says
>In the future, we’ll add more ways to specify a plugin, such as with a remote URL. This would use semantic versioning ranges to constrain the versions which can be used. When aspect runs, it can then prompt you to re-lock the dependencies to exact versions if they have changed, and can verify the integrity of the plugin contents against what was first installed.

**Comment by sluongng** [comment]
I took a look at this project today to investigate on how to create my own plugins, but I find the current plugin setup being a bit too complicated for my taste.

I prefer to have 1 single binary as the entry point, not `1 main binary + (1 binary for each plugin)`. I think there are value in having multiple plugins included in a self-contained binary. Some example of this include: telegraf, gazelle etc... The plugins can still be turned off/on via config file, but the distribution is a lot simpler (single binary) and the API are just Go interfaces instead of gRPC calls.

So I would suggest to consider a single binary system similar to gazelle's:

- Expose an `aspect_cli_binary` bazel rule for users to self-compile the whole binary (using bazel)
- Expose a `plugins` attribute in that rule where users can point to `go_library` that have an `AspectPlugin` struct export which implements all the interfaces required.
- The `aspect_cli_binary` rule constructs a new `plugins.go` file from Go template that import all the plugins, then re-export them as a go slice for the main library to consume.
- Final aspect binary is compiled using existing source and the generated `plugins.go` file.

This is exactly how Gazelle works with the `language.go` file today.

WDYT?

**Comment by alexeagle** [comment]
Yes we want to support this model in addition to "dynamic linked plugins", for DevX teams who are sophisticated enough to distribute the resulting binary. It's already possible but not documented and yeah there could be some custom Bazel rule to make it simple to construct.

FWIW we are developing a single Aspect plugin "bundle" with proprietary plugins, so there are exactly two programs to execute. But as an ecosystem of plugins gets developed, it's true that it's wasteful of resources to start many gRPC server sub processes

**Comment by gregmagolan** [comment]
@sluongng Work on this project got put aside while we focused on some other things but we're back to driving it to a MVP. We're likely to go with what you suggested back in June and compile in our pro plugins directly into a pro CLI binary and build this pattern into the open source core so that users of the open source CLI core can do the same.

@alexeagle You built and landed the functionality to pull plugin releases from a URL,

```
		// Syntax sugar:
		//   from: github.com/org/repo
		// is the same as
		//   from: https://github.com/org/repo/releases/download
		// Example release URL:
		//   https://github.com/aspect-build/aspect-cli-plugin-template/releases/download/v0.1.0/plugin-plugin-linux_amd64
```

https://github.com/aspect-build/aspect-cli/blob/345c57ac08a6f0be4a595a5a2b32a99dc39d0c78/pkg/plugin/client/client.go#L131

Closing this issue as done
