### ISSUE TITLE
Plugin Registration: Allow individual plugins to be configured from top-level config

### ISSUE THREAD

**Issue by dymart** [aspect-build/aspect-cli#223]
2 points difficulty 
Described here: https://hackmd.io/GKLazSQ3RU-aagWQoJJicg

**Comment by gregmagolan** [comment]
This isn't needed anymore. We opted to simplify things so the pro-plugin doesn't contain more plugins but instead contains features and those features are configured in their own namespaces.

Long term we'll hoist each pro-plugin feature to be their own top-level plugins but that are built into the pro cli binary and run in-process instead of over grpc.
