### ISSUE TITLE
help manage my disk space

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#32]
Bazel workspaces can occupy a lot of space. `bazel clean` will fix that, but first you have to know that Bazel is the reason you're low on disk, and how big each Bazel workspace is.

**Comment by alexeagle** [comment]
https://gist.github.com/mr-salty/a66119941e797d9eb49b15ea211ea968 has a recipe that might be useful

**Comment by JesseTatasciore** [comment]
- Dont want to parse the entire disk if we can avoid it
- A large number of bazel workspaces will be siblings to the bazel repo you are working on right now. Should be able to easily see those caches without checking the entire disk
- Want to remove some combination of largest / "longest since last used" bazel caches first
- Prompt user before removing anything
- Will need to support windows as well but can be done as a separate pass later. Make sure to make a ticket for tracking purposes

**Comment by alexeagle** [comment]
I think we can land this without the repository cache, and without looking for "other" disk cache. The current disk cache is fine.

Comment on the upstream bazelbuild issue where the disk-cache has no eviction. https://github.com/bazelbuild/bazel/issues/5139#issuecomment-941525571
